### ISSUE TITLE
I want to incliude information about Fedora and AMD GPUs

### ISSUE THREAD

**Issue by rlh100** [sethgoldin/install-davinci-resolve-centos#15]
I am working through the process of installing resolve with both Nvidia and AMD drivers.

I would like to modify your install instructions to cover these cases.  My proposed titles are:
install-davinci-resolve-fedora-nvidia
install-davinci-resolve-fedora-amd

Or maybe these should be combined into a single:
install-davinci-resolve-fedora

How would you recommend doing this in github?
A fork? A branch? A separate project?

Thanks
RLH

**Comment by sethgoldin** [comment]
Nice! I think forks are probably best, since you'll maintain those notes yourself for Fedora.

I think both `install-davinci-resolve-fedora-nvidia` and `install-davinci-resolve-fedora-amd` are good names.

Even though Fedora is in the Red Hat ecosystem and life cycle, new packages and kernels are changing all the time, and I'd be a bit concerned about stability there. I expect you might run into some headaches, but if you do get some systems up and running on Fedora, it'd be great to have that knowledge!
